### ISSUE TITLE
Display two authors instead of "Author 1 & al."

### ISSUE THREAD

**Issue by antoinentl** [loup-brun/hugo-cite#35]
Actually if a bibliographical reference have 2 authors, the citation display just the first, but it's useful to have both when there is less than 3 authors.

Current:  
![Capture d’écran de 2021-06-04 00-25-31](https://user-images.githubusercontent.com/6869488/120719922-21bce500-c499-11eb-914b-19f702c913b8.png)

Expected:  
![Capture d’écran de 2021-06-04 00-26-21](https://user-images.githubusercontent.com/6869488/120719972-39946900-c499-11eb-9764-bafffa5baacb.png)

**Comment by loup-brun** [comment]
This in-text citation style is more in line with **APA 6th edition**. APA 7th edition simply states: 1 author + _et al. — e.g. (Epron _& al._, 2016) — no matter how many authors (2, 3 or 25).

Thanks @HughP for bringing up the [differences](https://www.scribbr.com/apa-style/apa-seventh-edition-changes/) between APA 6 & 7. We will need to make a decision on this (see #34 for the discussion with publisher location for example).
