### ISSUE TITLE
Bug in recent two author fix

### ISSUE THREAD

**Issue by HughP** [loup-brun/hugo-cite#38]
Greetings @antoinentl & @loup-brun,

I just implemented the fix accepted and mentioned here https://github.com/loup-brun/hugo-cite/pull/36/commits/511d138852b1f3d9664cfa6cfaaa17141134ddea

I agree that the pattern shown in #35 for two authors is not a good pattern, in fact it is not APA 6th compliant. But worse I think is that it totally breaks display for cases with three authors. take a look at my screen shot, where I have changed the ` & al.` to `et al.` 

![results](https://user-images.githubusercontent.com/40230/120864774-0b905100-c58d-11eb-9dc2-7812f47c8905.png)

For reference on what APA 6th calls for in in-line citations here is their reference chart.

![number of authors](https://user-images.githubusercontent.com/40230/120864821-2236a800-c58d-11eb-8cb5-18cceaf3c8f6.png)

**Comment by loup-brun** [comment]
Uh-oh, will revert that merge and fix that.

**Comment by antoinentl** [comment]
Oups sorry for that @HughP !
