### ISSUE TITLE
Open source documentation site

### ISSUE THREAD

**Issue by loup-brun** [loup-brun/hugo-cite#5]
Open source the [documentation site](https://labs.loupbrun.ca/hugo-cite/).

In this repo? (~~`exampleSite`~~ `docs`?)
Elsewhere?

**Comment by antoinentl** [comment]
Before you implemented the theme and submodules installation I thought that it was interesting and helpful to add the source here, but now I think a separate repo would be more relevant.

And so with a repo we can add a link to the source, very useful to understand how the demo works :+1:

**Comment by loup-brun** [comment]
see [`docs`](https://github.com/loup-brun/hugo-cite/tree/docs) branch.

maybe keep docs in separate branch? (to avoid cloning docs when just downloading production files)?

**Comment by loup-brun** [comment]
Kept in docs branch.
