### ISSUE TITLE
cite shortcode produces complete ref info for in-line citation

### ISSUE THREAD

**Issue by lzachmann** [loup-brun/hugo-cite#52]
Hi @loup-brun! I'm excited about using this theme as an add on. I've done my best to follow your instructions, but I am seeing too much info appear when invoking the cite shortcode in a page. For example:

![Screen Shot 2021-08-11 at 9 03 44 AM](https://user-images.githubusercontent.com/7574887/129054822-2a6ea27f-bf15-4fbe-86ce-16868029d0f2.png)

when it should just read "(Link & Sauer, 1998)". Have you seen this before? Perhaps I am missing something embarrassingly simple. I'd be happy to share the Hugo site itself if necessary. Thanks in advance!

**Comment by antoinentl** [comment]
It seems that the CSS specific to Hugo Cite is not called :thinking:. Can you check that [the style sheet](https://github.com/loup-brun/hugo-cite/blob/master/static/hugo-cite.css) is well integrated?

**Comment by lzachmann** [comment]
🤦 it wasn't getting pulled into the head perviously. Your hint was all I needed to fix the issue. Thanks so much!
