### ISSUE TITLE
Suppress reference title

### ISSUE THREAD

**Issue by lzachmann** [loup-brun/hugo-cite#55]
Hey @loup-brun, this is a stellar module! I was wondering if there's an easy way to suppress printing the "title" of each reference. For instance, on rendering {{< cite "link1998estimating" >}} with {{< bibliography cited >}}, I see:

__Link & Sauer (1998)__
Link, W. & Sauer, J. (1998). Estimating population change from count data: Application to the north american breeding bird survey. Ecological applications, 8(2). 258–268.

Is there any way to silence the bold-face __Link & Sauer (1998)__? I think all I actually need is just the citation....

**Comment by antoinentl** [comment]
Hi @lzachmann. You can add some CSS on the class `appel`, like:

```
.appel {
    display: none;
}
```

Not sure if it's the best way, but it works and it's light.

**Comment by lzachmann** [comment]
Worked perfectly! 🙏

**Comment by HughP** [comment]
This tip should go in the documentation somewhere... it's really useful.
