### ISSUE TITLE
Publish bib.json file used for the bibliography demo

### ISSUE THREAD

**Issue by ghost** [loup-brun/hugo-cite#59]
Could you please publish the bib.json file that you have used in this demo: https://labs.loupbrun.ca/hugo-cite/demo/

Thanks :)

**Comment by loup-brun** [comment]
All the demo files can be found on the [`docs`](https://github.com/loup-brun/hugo-cite/tree/docs) branch: https://github.com/loup-brun/hugo-cite/blob/docs/docs/bib.json

;)
