### ISSUE TITLE
Where to add CSS to HTML templates

### ISSUE THREAD

**Issue by TimothyElder** [loup-brun/hugo-cite#63]
Where should the following line go "<link rel="stylesheet" type="text/css" href="{{ "/hugo-cite.css" | relURL }}" />"?

I placed it in a file called "bib.html" in the layouts directory of my hugo site and I am getting citation/bibliography content, but it is not formatted correctly.

**Comment by HughP** [comment]
That line of code should be placed in the HTML header of your theme.
Usually, or well written, themes have partial for custom includes to the
HTML header. OR they place the theme files in the fallback position and
have a place for the site manager to hold modified versions of  theme file.
The idea is that original theme files would be overwritten in an upgrade.

**Comment by TimothyElder** [comment]
Thanks! Inserting the code pretty much anywhere in `./themes/my-theme/layouts/partials/header.html` worked and the formatting is correct now.
