### ISSUE TITLE
Hugo-cite remove 'Retrieved from'

### ISSUE THREAD

**Issue by urspx** [loup-brun/hugo-cite#65]
(Crap, I'm sorry! This was meant to go in an internal issue tracker, as a to-do for customising our installation of Hugo-cite. It's an amazing project, I really love it!)

**Comment by HughP** [comment]
Right on. FYI: The current iteration is based on APA version 6, which does have that text. The APA did have a similar opinion as you did and so in APA 7 they got rid of it.
