### ISSUE TITLE
Differentiate the point paginations (p. 10) from the passages (pp. 10-15)

### ISSUE THREAD

**Issue by antoinentl** [loup-brun/hugo-cite#9]
Actually hugo-cite, and in particular the shortcodes `cite.html`, is set up for the passages between one page to another indicated with a double "pp". But we need to cite with just a page indicated with a single "p".

For the implementation we can use the indication of the `-`.

**Comment by loup-brun** [comment]
Yes! Usage examples:

- `{{< cite Fauchie2020 20 >}}` -> (Fauchié, 2020, p. 20)
- `{{< cite Fauchie2020 20-22 >}}` -> (Fauchié, 2002, pp. 20-22)

**Comment by antoinentl** [comment]
Perfect :100:
